import Foundation

// MARK: - StubTranscriber

/// Placeholder transcriber. Returns deterministic dummy text so the pipeline
/// and UI can be exercised before Whisper is wired in.
public struct StubTranscriber: Transcriber {
    public init() {}

    public func transcribe(audioURL: URL, recordingId: UUID) async throws -> Transcript {
        let sentences = [
            "Welcome to Notova, this is a stub transcript.",
            "We need to follow up with the design team next week.",
            "Please send the updated budget by Friday.",
            "The on-device model will replace this placeholder soon."
        ]
        var segments: [TranscriptSegment] = []
        var cursorMs = 0
        for sentence in sentences {
            let durationMs = max(1500, sentence.count * 60)
            segments.append(
                TranscriptSegment(
                    startMs: cursorMs,
                    endMs: cursorMs + durationMs,
                    text: sentence,
                    speaker: "Speaker 1"
                )
            )
            cursorMs += durationMs
        }
        return Transcript(
            recordingId: recordingId,
            language: "en",
            fullText: sentences.joined(separator: " "),
            segments: segments
        )
    }
}

// MARK: - StubSummarizer

/// Placeholder summarizer. Produces templated markdown and extracts naive action
/// items from sentences containing action verbs.
public struct StubSummarizer: Summarizer {
    public static let modelName = "stub-summarizer-v1"

    /// Verbs that mark a sentence as a likely action item.
    public static let actionVerbs: Set<String> = [
        "follow", "send", "schedule", "review", "email", "call",
        "prepare", "update", "share", "complete", "finish", "create",
        "draft", "remind", "book", "confirm", "submit"
    ]

    public init() {}

    public func summarize(_ transcript: Transcript, style: String) async throws -> Summary {
        let sentences = Self.splitSentences(transcript.fullText)
        let actionItems = Self.extractActionItems(from: sentences)

        var markdown = "## Summary (\(style))\n\n"
        markdown += "_Generated by \(Self.modelName) — replace with Gemma 3n E4B on-device._\n\n"
        if let first = sentences.first {
            markdown += "**Overview:** \(first)\n\n"
        }
        markdown += "### Key points\n"
        for sentence in sentences.prefix(3) {
            markdown += "- \(sentence)\n"
        }
        if !actionItems.isEmpty {
            markdown += "\n### Action items\n"
            for item in actionItems {
                markdown += "- [ ] \(item.text)\n"
            }
        }

        return Summary(
            recordingId: transcript.recordingId,
            style: style,
            contentMarkdown: markdown,
            actionItems: actionItems,
            model: Self.modelName
        )
    }

    public static func splitSentences(_ text: String) -> [String] {
        text
            .components(separatedBy: CharacterSet(charactersIn: ".!?"))
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty }
    }

    public static func extractActionItems(from sentences: [String]) -> [ActionItem] {
        sentences.compactMap { sentence in
            let words = sentence.lowercased().split(whereSeparator: { !$0.isLetter })
            let hasVerb = words.contains { actionVerbs.contains(String($0)) }
            guard hasVerb else { return nil }
            return ActionItem(text: sentence)
        }
    }
}

// MARK: - Stub engine conformances

/// The stubs are always available, so they serve as the guaranteed fallback for
/// the resolvers. Real engines (Apple Speech / Foundation Models / MLX Gemma)
/// live in their packages and report availability dynamically.
extension StubTranscriber: TranscriptionEngine {
    public var engineName: String { "Built-in sample transcriber" }
    public func isAvailable() async -> Bool { true }
}

extension StubSummarizer: SummarizationEngine {
    public var engineName: String { "Built-in sample summarizer" }
    public func isAvailable() async -> Bool { true }
}

// MARK: - StubIntegrationExporter

/// Placeholder exporter that pretends to push a note to an external provider.
public struct StubIntegrationExporter: IntegrationExporter {
    public let provider: String

    public init(provider: String = "stub") {
        self.provider = provider
    }

    public func export(
        recordingId: UUID,
        summary: Summary,
        transcript: Transcript
    ) async throws -> IntegrationExport {
        IntegrationExport(
            recordingId: recordingId,
            provider: provider,
            externalId: UUID().uuidString,
            url: "https://example.com/\(provider)/\(recordingId.uuidString)",
            status: .done
        )
    }
}
